### ISSUE TITLE
If using older zlib on Linux, can add -DNOCRYPT

### ISSUE THREAD

**Issue by cgodkin** [F2I-Consulting/Minizip#2]
This is just a note that you might want to add to README.md if you think it's useful.

Our RHEL 6 machines have zlib.h version 1.2.3 so zip.c will not compile because the type z_crc_t is undefined.  An easy fix, since I don't think I care about encrypting RESQML packages, is to simply compile on Linux with -DNOCRYPT.

RHEL 7 seems to have zlib.h version 1.2.7 which does have the z_crc_t type however.

carl

**Comment by philippeVerney** [comment]
Thanks for the info.

I just added it to the README.md.
FYI, it looks there is a RPM for CENTOS6 http://mirror.centos.org/centos/6/os/x86_64/Packages/minizip-devel-1.2.3-29.el6.x86_64.rpm but you probably cannot install it (admin rights).
