### ISSUE TITLE
up-to-date?

### ISSUE THREAD

**Issue by Neustradamus** [F2I-Consulting/Minizip#5]
Hello @F2I-Consulting team,

I am not sure that the code is up-to-date.

Maybe good to look?

Regards.

**Comment by philippeVerney** [comment]
Hi @Neustradamus 

Good catch : https://github.com/madler/zlib/compare/v1.2.11...v1.2.13#diff-ced292df6503e2a0fc6c34998acdc67ab4deffe879c29f08313c84da816c338b
There are some updates to minizip in latest zlib (1.2.13) compared to zlib 1.2.11 which is the current one.

A more general update (regarding FESAPI) would be to switch to libarchive or minizip-ng but not enough added value for now for such a work.
